### ISSUE TITLE
Restore Tracking code

### ISSUE THREAD

**Issue by andreaskas** [presscustomizr/hueman#106]
@AlxMedia please, restore the tracking code option. Setting up a tracking code now requires file edit or an extra plugin, so i think it's a must have option to avoid extra complexity.

**Comment by signaleleven** [comment]
Just out of curiosity, @AlxMedia , why was it removed?
I consider it "plugin territory", so I was not hurt by it. Was that also your reasoning?

**Comment by Osiwaru** [comment]
+1.
Still running 2.2.2 with hope, that tracking code will be back in 2.2.4.

**Comment by elliot-labs** [comment]
You can use a plugin to insert your tracking code. I use the Yost SEO plugin. It is not a manual edit thing. It will take care of your issues for you. I don't have this issue because I use that plugin.

**Comment by andreaskas** [comment]
What's the point of installing an additional plug-in for an operation that this theme was offering? Let @AlxMedia inform us for the reason he removed it. If there isn't any major issue or conflict or anything similar, it would be nice to restore it...

**Comment by elliot-labs** [comment]
My personal opinion is to keep everything separate and not manually edit files:
themes are for looks,
plugins are for functions.

Especially if the theme gets updated, the changes will be lost. Wordpress was designed around not having to edit the files and it is discouraged but because of popular outcry the created something called Child Themes. So if a feature was there in the past then you can add it using a child theme.

Even so this second solution does not require the theme to be updated. Just add it to the child theme. It will be persistent after updates unlike the current tracking code.
