### ISSUE TITLE
SEO Breadcrumbs

### ISSUE THREAD

**Issue by elliot-labs** [presscustomizr/hueman#112]
Can you add support for breadcrumbs?

Here is the code for the Yoast SEO plugin:
`<?php if ( function_exists('yoast_breadcrumb') ) {
    yoast_breadcrumb('<p id="breadcrumbs">','</p>');
} ?>`

It is supposed to go in templates.

reference link:
https://yoast.com/wordpress/plugins/breadcrumbs/

Thanks!

**Comment by keunes** [comment]
Hi there,

Although supporting breadcrumbs would be nice, I don't think @AlxMedia will add this specific piece of code as it *specific for an external plugin* (and I guess it is unwanted to discriminate against [other](https://www.elegantthemes.com/blog/tips-tricks/how-to-add-breadcrumbs-to-your-wordpress-website) [options](http://colorburned.com/adding-custom-breadcrumbs-into-your-wordpress-theme/).

In order to get this plugin working, you may need to create a [child theme](https://codex.wordpress.org/Child_Themes) in which you put the code you provided (although the plugin's successor [doesn't seem to need a code to be implemented](http://kb.yoast.com/article/119-installation-guide-for-wordpress-seo)).

**Comment by elliot-labs** [comment]
I understand. I was giving an example of what some of the breadcrumb code
could be. I agree and currently do that.

On Tue, May 19, 2015 at 5:12 AM, keunes <notifications@github.com> wrote:

> Hi there,
>
> Although supporting breadcrumbs would be nice, I don't think @AlxMedia
> <https://github.com/AlxMedia> will add this specific piece of code as it *specific
> for an external plugin* (and I guess it is unwanted to discriminate
> against other
> <https://www.elegantthemes.com/blog/tips-tricks/how-to-add-breadcrumbs-to-your-wordpress-website>
> options
> <http://colorburned.com/adding-custom-breadcrumbs-into-your-wordpress-theme/>
> .
>
> In order to get this plugin working, you may need to create a child theme
> <https://codex.wordpress.org/Child_Themes> in which you put the code you
> provided (although the plugin's successor doesn't seem to need a code to
> be implemented
> <http://kb.yoast.com/article/119-installation-guide-for-wordpress-seo>).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AlxMedia/hueman/issues/112#issuecomment-103409976>.
>



-- 
Everybody talks about the weather but they do nothing about it - Mark Twain

Elliot Huffman

DISCLAIMER:
This e-mail is for the intended recipient(s) only

If you have received it by mistake please let me know by reply and then
delete it from your system; access, disclosure, copying, distribution or
reliance on any of it by anyone else is prohibited.

If you as intended recipient have received this e-mail incorrectly, please
notify the sender (via e-mail) immediately.

**Comment by keunes** [comment]
:thumbsup:

**Comment by fwolfst** [comment]
Native breadcrumb support by the theme (or plugin) would be great (I will probably go down the yoast path, too) - if that is not going to happen this issue should be closed.

**Comment by fwolfst** [comment]
Fwiw, I sketched superbasic breadcrumbs (overwriting `parts/page-title.php`) here:
https://github.com/ecovillage/hueman-7l-child/commit/825ae41ecfdb873e5cd9d7846e28d76b050bb14a
.  The relevant changes are marked. This will only put breadcrumbs on "Pages".
