### ISSUE TITLE
Effect/Plans of new Hueman developer?

### ISSUE THREAD

**Issue by keunes** [presscustomizr/hueman#150]
Already a while ago I saw someone else accepting some merge requests. Now I noticed that the ownership of the repository has changed. Started googling and found that indeed @AlxMedia after years (?) of great work (for which many, many thanks!) [found a new home for Hueman](http://alxmedia.se/2015/12/hueman-finds-a-new-home/).

Now I wonder what plans the new developer (@Nikeo) has with this theme. As it's a GPLv3-licensed product, I assume it will remain open source. But are there any changes we can expect? Are there development plans for specific features, or should we expect bug-fixes only, for example?

Curious to hear :)

**Comment by jaylinski** [comment]
I'm curious too.

**Comment by Nikeo** [comment]
Hi!
Yes I'm taking over the dev of the Hueman theme. It will of course remain GPL licensed and available on WordPress.org.
The first step will be to move all settings from the current admin option panel to the customizer, since this is required for all themes on wp.org.
I'll publish a post in the coming days to explain in details how we'll work on Hueman. Everything will be done to make the transition as smooth as possible for the user community of the Hueman theme. For example, all existing settings won't be changed of course.
Stay tuned :)
