### ISSUE TITLE
Why you remove theme action and filters?

### ISSUE THREAD

**Issue by Goback** [presscustomizr/hueman#206]
Hello,
in previous versions seems to were many useful action and filters , and my child theme also was using that's,
why you omit this useful feature from the code?what happened?

**Comment by robbinhood** [comment]
@Goback - can you provide an example of an action or filter that you were using previously that's not currently available?

**Comment by Goback** [comment]
i was downloaded from alxmedia.se ,  it's seems to be different from github's one,and i saw that there is no any like theme in his site.
i was using `hue_after_nav_header`  action to add my custom menu after header.
i don't know what happened really!  i'm confused!
here is the child theme header provided with this theme that i have already:
```
/*
Theme Name: Hueman Child
Theme URI: http://alxmedia.se/themes/hueman/
Description: Sample child theme for customization.
Author: You
Author URI: 
Template: hueman
Version: 1.0.0
*/
```

**Comment by Nikeo** [comment]
Hi @Goback, no filter or action hooks have been removed from the new versions.

If a hook does not exist at a location where you need to embed a custom content, then you'll need to override the origina template file with your own template in a child theme,

The future versions of the theme will include more structural action hooks to help users embedding dynamic content in their website.

Since this is not an issue, I need to close this thread on Github. Please open a new topic in the forum about this : https://wordpress.org/support/theme/hueman

thanks :)
