### ISSUE TITLE
RSS Feed Broken

### ISSUE THREAD

**Issue by robbinhood** [presscustomizr/hueman#256]
User reports RSS feed causes the RSS feed meta tag to be blank.
https://wordpress.org/support/topic/rss-feed-broken-27

**Comment by Nikeo** [comment]
ok thanks for reporting Bruce

**Comment by robbinhood** [comment]
Also breaks rss feeds registered by plugins as reported here:
https://wordpress.org/support/topic/bug-reportrequest-please-dont-break-rss-feeds

**Comment by boderhamster** [comment]
Hi Guys, 
I'm using the Theme and I love it. 
But I'm currently thinking to change my theme, because of this bug. As it makes it impossible for a lot of people to read my articles and listen to my podcasts.

But of cause that is a lot of work. So I'm wondering: Can you give me an advice about this? Will this be fixed soon? Is this the kind of issue that just gets fixed with the next update, or is this difficult to do?

Thanks in advance. 
Yours
Dominik

**Comment by Nikeo** [comment]
Hi, thanks for the reminder about this problem.

Should be fixed in v3.1.7. Release note here : https://github.com/presscustomizr/hueman/releases

**Comment by boderhamster** [comment]
Hi Guys, 
thanks for the update. My feed for the podcast is now working.
But my regular RSS-Feed is still blank:
http://nerdmeetsyou.de/feed/
Is there anything I can do about this?

yours
Dominik

**Comment by eteubert** [comment]
@boderhamster Works for me. Maybe you were just looking at a cached version of the broken feed.

**Comment by Nikeo** [comment]
@boderhamster works here too. Can you refresh your browser cache or try on another brother ?
Can you check if you have a cache plugin setting that could be caching this page for some reason ( normally not but I don't know all of them ).

**Comment by boderhamster** [comment]
Hi, 
it works in my RSS-Reader, but when viewing it in my browser (with emptied cache) I see this:
![unbenannt](https://cloud.githubusercontent.com/assets/8282516/17979584/ac5806ce-6afb-11e6-9b06-260039dba598.PNG)
