### ISSUE TITLE
Thumbnail issue in Most Popular Tab of Hueman Dynamic Tabs Widget ( Load images on scroll )

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/hueman#376]
Hi,

Please see this forum thread.
https://wordpress.org/support/topic/thumbs-in-dynamic-tabs-widget-dont-show-until-page-scroll/#post-8587926

I am able to replicate the issue.

When website option is set to load images on scroll. 
Some thumbnail images on Most Popular Tab of Hueman Dynamic Tabs Widget does not show up when website loads.
Needs to scroll in order for thumbnail images to show up.

This is not correct behavior, because the widget is in view when web page has loaded. 
The thumbnail images should show up without scrolling.

Please see my screen-cast.
http://screencast-o-matic.com/watch/cDlO1OQUBn

Thank you

**Comment by eri-trabiccolo** [comment]
Hi Denzel,
thanks for reporting this.
Can reproduce the issue (which happens when the tabs default order is changed) and makes totally sense.
@nikeo , to fix this we need:
1) custom event for the img smartload so that we can "maybe load" images when needed (*)
2) trigger the above event on tabs init ( and on tab active toggle )
3) (not related to this issue) would make sense trigger the above event also when uncollapsing sidebars in mobiles.

(*) we might even use the 'scroll' or 'resize' bundled event, but those will possibly fire a lot of reactions we don't want.

**Comment by Nikeo** [comment]
OK. Yep, needs a fix.
@eri-trabiccolo solutions sounds perfect.
