### ISSUE TITLE
missing author tag in hCard / hEntry causing rankings to drop after Google detects hundreds of errors

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/hueman#421]
> Hello I ve been wondering for weeks why my indexed pages dropped dramatically in Google search Console, and this is linked to your theme Hueman that i just installed and has missing hcard "author". My Google console has started to show me a huge number of errors and in the meantime my indexed pages has completely dropped...
> 
> Can you please let me know if you have planned to fix this issue already? many thanks!!!

**Comment by Sh4d0wHunt3rX** [comment]
Hi
Just want to know did you fix these?
Missing: updated
Missing: author

Thanks

**Comment by ghost** [comment]
Hi @amiremami  are you experiencing any problems with structured data ?

**Comment by Sh4d0wHunt3rX** [comment]
Sorry I didn't notice the version you fixed this, because my version is 3.3.4 and it's old.

But the structured data option you provided in the theme (customization section) also not working. When I enable that option no tags add to the theme.

I also couldn't see these tags on your demo in your source code. For example here:
https://demo-hueman.presscustomizr.com/gabrielle-aplin-with-the-power-of-love/

I'm not sure if you turned on this feature in demo. These tags are JSON+LD?

For example here, this option has been enabled:
https://ajibtarin.mywpstaging.site/strange-technology/12395

But I can't see any schema structured tags which is related to your theme.

Thanks

**Comment by Sh4d0wHunt3rX** [comment]
No solution for this @Nikeo ? :)
