### ISSUE TITLE
WooCommerce V3.0 and Flexslider

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/hueman#427]
https://wordpress.org/support/topic/no-images-in-index-scroller-after-update/#post-9000081

**Comment by Nikeo** [comment]
Hi @eri-trabiccolo since you're working on WC compat, could you have a look to this one when you get the chance ?
thank you

'd

**Comment by eri-trabiccolo** [comment]
Ah,
just checked it worked on the product, I thought there would have been an issue there but not in home :D

**Comment by eri-trabiccolo** [comment]
Not able to reproduce this issue on my side.
Anyway...
1) flexslider hueman's version has no rtl option
2) woocommerce's version has rtl option and it forces to true when no rtl option is passed and the html direction is rtl
3) because of the same script handle name (flexslider), when woocommerce is enabled the woocommerce's flexslider is loaded instead of the hueman's one (because of the registering order)

These points makes useless for us to pass the rtl option.
I don't think that's the real problem.

The only thing in 3) that maybe can cause problems is the fact that woocommerce's flexslider is printed in the footer, while we use to print it in the header... but we fire the slider on document ready so..

No clue honestly :(

**Comment by eri-trabiccolo** [comment]
See the discussion on wp.org
The real problem is that the flexslider never displayed fine on rtl websites.
It needed some CSS rules which are not needed anymore, or better are in conflict, with the latest flexslider rtl behaviour (rtl param added in 2.6.1).
